# Read in battles.csv, add column headers

battles.csv represents our dataset with all battles from top 100 players of each region crawled during april 2024 - september 2024.

First we assign headers to our columns and print the dimensions of our data.

In [120]:
import pandas as pd

In [121]:
df = pd.read_csv('/content/battles.csv', header=None)

df.columns = ['id', 'battle_time', 'game_mode', 'p1_tag', 'p1_trophies', 'p1_best_trophies', 'p1_wins',
              'p1_losses', 'p1_battle_count', 'p1_crowns', 'p1_elixir_leaked', 'p1_cards', 'p1_support_cards',
              'p2_tag', 'p2_trophies', 'p2_best_trophies', 'p2_wins', 'p2_losses', 'p2_battle_count',
              'p2_crowns', 'p2_elixir_leaked', 'p2_cards', 'p2_support_cards']

In [122]:
print("(Number of battles, number of columns): ", df.shape)

df.head()

(Number of battles, number of columns):  (88883, 23)

,id,battle_time,game_mode,p1_tag,p1_trophies,p1_best_trophies,p1_wins,p1_losses,p1_battle_count,p1_crowns,...,p2_tag,p2_trophies,p2_best_trophies,p2_wins,p2_losses,p2_battle_count,p2_crowns,p2_elixir_leaked,p2_cards,p2_support_cards
0,1,2024-04-08 14:32:06.000000,Ladder,2J200GLG8,6911,6942,3336,2107,9197,1,...,29LC802RC,6860,6860,3174,2892,7839,0,3.00,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
1,3,2024-04-08 14:28:14.000000,Ranked1v1,2J200GLG8,6911,6942,3336,2107,9197,1,...,PG0Q0Y0L9,6708,6708,3312,3994,8177,0,1.75,"[{""name"": ""Valkyrie"", ""id"": 26000011, ""level"":...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
2,4,2024-04-08 15:29:20.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,1,...,CLPC08L0,9000,9000,17541,14990,35975,3,4.64,"[{""name"": ""Royal Recruits"", ""id"": 26000047, ""l...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
3,5,2024-04-08 15:24:27.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,3,...,2YQP0GYVQ,9000,9000,1261,1015,2301,2,8.18,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Dagger Duchess"", ""id"": 159000002, ""..."
4,6,2024-04-08 15:20:10.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,2,...,8R0RPQJVV,9000,9000,16221,12945,38004,1,4.41,"[{""name"": ""Bats"", ""id"": 26000049, ""level"": 14,...","[{""name"": ""Cannoneer"", ""id"": 159000001, ""level..."

# Filter game mode and draw matches

Then we filter the `game_mode` column. We only include battles with the `game_mode` containing `Ladder` or `Ranked`. We also exclude certain specific game modes, namely ..., as they do not represent competitive battles between players. Instead, they are casual game modes intended for fun, where players may have experimented with different card compositions and played less seriously. Our dataset is filtered to include only competitive battles, where players are matched with opponents of similar skill levels. We focus solely on analyzing these matches.

In [123]:
df = df[df['game_mode'].str.contains('Ladder|Ranked', na=False) &
        ~df['game_mode'].str.contains('7xElixir_Ladder|Goblin_Ladder|Rage_Ladder|CrownRush|TripleElixir|Overtime', na=False)]

df = df[df['p1_crowns'] != df['p2_crowns']]

game_mode_counts = df['game_mode'].value_counts()
print(game_mode_counts)

game_mode
Ranked1v1_NewArena             23575
Ranked1v1_NewArena_GoldRush    15774
Ladder_GoldRush                 3312
Ladder                          3265
RampUpElixir_Ladder              826
Ranked1v1                        771
Ranked1v1_GoldRush               227
DoubleElixir_Ladder                4
Name: count, dtype: int64

In [124]:
print("(Number of battles, number of columns): ", df.shape)
print("Column headings: ", df.columns)

df.head()

(Number of battles, number of columns):  (47754, 23)
Column headings:  Index(['id', 'battle_time', 'game_mode', 'p1_tag', 'p1_trophies',
       'p1_best_trophies', 'p1_wins', 'p1_losses', 'p1_battle_count',
       'p1_crowns', 'p1_elixir_leaked', 'p1_cards', 'p1_support_cards',
       'p2_tag', 'p2_trophies', 'p2_best_trophies', 'p2_wins', 'p2_losses',
       'p2_battle_count', 'p2_crowns', 'p2_elixir_leaked', 'p2_cards',
       'p2_support_cards'],
      dtype='object')

,id,battle_time,game_mode,p1_tag,p1_trophies,p1_best_trophies,p1_wins,p1_losses,p1_battle_count,p1_crowns,...,p2_tag,p2_trophies,p2_best_trophies,p2_wins,p2_losses,p2_battle_count,p2_crowns,p2_elixir_leaked,p2_cards,p2_support_cards
0,1,2024-04-08 14:32:06.000000,Ladder,2J200GLG8,6911,6942,3336,2107,9197,1,...,29LC802RC,6860,6860,3174,2892,7839,0,3.00,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
1,3,2024-04-08 14:28:14.000000,Ranked1v1,2J200GLG8,6911,6942,3336,2107,9197,1,...,PG0Q0Y0L9,6708,6708,3312,3994,8177,0,1.75,"[{""name"": ""Valkyrie"", ""id"": 26000011, ""level"":...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
2,4,2024-04-08 15:29:20.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,1,...,CLPC08L0,9000,9000,17541,14990,35975,3,4.64,"[{""name"": ""Royal Recruits"", ""id"": 26000047, ""l...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
3,5,2024-04-08 15:24:27.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,3,...,2YQP0GYVQ,9000,9000,1261,1015,2301,2,8.18,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Dagger Duchess"", ""id"": 159000002, ""..."
4,6,2024-04-08 15:20:10.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,2,...,8R0RPQJVV,9000,9000,16221,12945,38004,1,4.41,"[{""name"": ""Bats"", ""id"": 26000049, ""level"": 14,...","[{""name"": ""Cannoneer"", ""id"": 159000001, ""level..."

# Remove afk matches

In our next step, we filter out battles, that could distort our dataset due to one player not playing the entire battle or experiencing internet connection loss during the battle. We don't want to remove battles, where one player has left the game, since he realized he could not win it anymore.

Technically we can detect such battles by observing the columns `p1_elixir_leaked` and `p2_elixir_leaked`. They indicate, that how many seconds each player has overloaded it's elixir (currency for placing cards). If a player does not place a card into the battle field, then this value increases by one every second and by two at the last minute of the battle. If one player experiences internet connection loss or gives up, then we should see, that the difference of `p1_elixir_leaked` and `p2_elixir_leaked` is not a small number. We decide, that we want to filter out a match, if the difference of leaked elixir is greater 20. We don't want to set this number too low, since there could be tactical reasons, why one player would not place a card. Additionally we only consider a match to be mean to filtered out, if the player, that hasn't placed cards for too long, has not managed to destroy one tower of the enemy. This would result in at least one crown for this player. This condition is added to not throw out battles out of the dataset, where one player has given up, but not because he lost connection or other reasons, but because he did not see a chance of winning the battle.

TODO: Maybe determine the critical difference in leaked elixir more scientifically.

In [125]:
# Calculate diff
df['elixir_diff'] = abs(df['p1_elixir_leaked'] - df['p2_elixir_leaked'])

# Battles where elixir_leaked difference > 20
df['elixir_diff_gt_20'] = df['elixir_diff'] > 20

In [126]:
# Which player has higher elixir?
def higher_elixir_leaked(row):
    if row['p1_elixir_leaked'] > row['p2_elixir_leaked']:
        return 'p1'
    elif row['p1_elixir_leaked'] < row['p2_elixir_leaked']:
        return 'p2'
    else:
        return 'equal'

df['higher_elixir_leak_player'] = df.apply(higher_elixir_leaked, axis=1)

In [127]:
# Has higher elixir_leaked player 0 crowns?
def higher_elixir_zero_crowns(row):
    if not row['elixir_diff_gt_20']:
        return False
    if row['higher_elixir_leak_player'] == 'p1':
        return row['p1_crowns'] == 0
    elif row['higher_elixir_leak_player'] == 'p2':
        return row['p2_crowns'] == 0
    else:
        return False

# Mark rows to delete
df['remove_battle'] = df.apply(higher_elixir_zero_crowns, axis=1)

In [128]:
# Filter out battles where remove_battle is True
df = df[~df['remove_battle']].reset_index(drop=True)

In [129]:
# Drop helper columns
df = df.drop(columns=['elixir_diff', 'elixir_diff_gt_20', 'higher_elixir_leak_player', 'remove_battle'])

In [130]:
print("(Number of battles, number of columns): ", df.shape)
df.head()

(Number of battles, number of columns):  (46534, 23)

,id,battle_time,game_mode,p1_tag,p1_trophies,p1_best_trophies,p1_wins,p1_losses,p1_battle_count,p1_crowns,...,p2_tag,p2_trophies,p2_best_trophies,p2_wins,p2_losses,p2_battle_count,p2_crowns,p2_elixir_leaked,p2_cards,p2_support_cards
0,1,2024-04-08 14:32:06.000000,Ladder,2J200GLG8,6911,6942,3336,2107,9197,1,...,29LC802RC,6860,6860,3174,2892,7839,0,3.00,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
1,3,2024-04-08 14:28:14.000000,Ranked1v1,2J200GLG8,6911,6942,3336,2107,9197,1,...,PG0Q0Y0L9,6708,6708,3312,3994,8177,0,1.75,"[{""name"": ""Valkyrie"", ""id"": 26000011, ""level"":...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
2,4,2024-04-08 15:29:20.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,1,...,CLPC08L0,9000,9000,17541,14990,35975,3,4.64,"[{""name"": ""Royal Recruits"", ""id"": 26000047, ""l...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""..."
3,5,2024-04-08 15:24:27.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,3,...,2YQP0GYVQ,9000,9000,1261,1015,2301,2,8.18,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Dagger Duchess"", ""id"": 159000002, ""..."
4,6,2024-04-08 15:20:10.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,2,...,8R0RPQJVV,9000,9000,16221,12945,38004,1,4.41,"[{""name"": ""Bats"", ""id"": 26000049, ""level"": 14,...","[{""name"": ""Cannoneer"", ""id"": 159000001, ""level..."

# Export the .csv for website
We add additional two columns for the website with dates. This is necessary to match out SQL table for our website.

In [131]:
df_for_web = df.copy()

df_for_web['created_at'] = "2024-08-27 00:00:00.000000"
df_for_web['updated_at'] = "2024-08-27 00:00:00.000000"

df_for_web.drop('id', axis=1)
df_for_web.to_csv('battles_for_website.csv', index=False, header=False)

In [132]:
df_for_web.drop('id', axis=1)
df_for_web.head(1)

,id,battle_time,game_mode,p1_tag,p1_trophies,p1_best_trophies,p1_wins,p1_losses,p1_battle_count,p1_crowns,...,p2_best_trophies,p2_wins,p2_losses,p2_battle_count,p2_crowns,p2_elixir_leaked,p2_cards,p2_support_cards,created_at,updated_at
0,1,2024-04-08 14:32:06.000000,Ladder,2J200GLG8,6911,6942,3336,2107,9197,1,...,6860,3174,2892,7839,0,3.0,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""...",2024-08-27 00:00:00.000000,2024-08-27 00:00:00.000000

# Elixir leaked normalization

In [81]:
# Normalize 'p1_elixir_leaked' and 'p2_elixir_leaked'
columns_to_normalize = ['p1_elixir_leaked', 'p2_elixir_leaked']

In [82]:
# min-max normalization
for column in columns_to_normalize:
    min_value = df[column].min()
    max_value = df[column].max()

    if max_value - min_value != 0:
        df[column + '_normalized'] = ((df[column] - min_value) / (max_value - min_value)).round(2)
    else:
        df[column + '_normalized'] = 0

In [83]:
# Drop the original columns
df = df.drop(columns=columns_to_normalize)

# Rename normalized columns
normalized_columns = {column + '_normalized': column for column in columns_to_normalize}
df = df.rename(columns=normalized_columns)

In [84]:
print(df)

          id                 battle_time           game_mode     p1_tag  \
0          1  2024-04-08 14:32:06.000000              Ladder  2J200GLG8
1          3  2024-04-08 14:28:14.000000           Ranked1v1  2J200GLG8
2          4  2024-04-08 15:29:20.000000           Ranked1v1  RJCYQLJJ0
3          5  2024-04-08 15:24:27.000000           Ranked1v1  RJCYQLJJ0
4          6  2024-04-08 15:20:10.000000           Ranked1v1  RJCYQLJJ0
...      ...                         ...                 ...        ...
46529  88872  2024-10-01 20:56:31.000000  Ranked1v1_NewArena   L00QJUYV
46530  88873  2024-10-01 20:53:16.000000  Ranked1v1_NewArena   L00QJUYV
46531  88874  2024-10-01 20:49:12.000000  Ranked1v1_NewArena   L00QJUYV
46532  88879  2024-10-01 20:41:24.000000              Ladder  2RRC9C0J2
46533  88884  2024-10-01 17:16:40.000000  Ranked1v1_NewArena  P92YLRP8Y

       p1_trophies  p1_best_trophies  p1_wins  p1_losses  p1_battle_count  \
0             6911              6942     3336       2107             9197
1             6911              6942     3336       2107             9197
2             9000              9000     4737       4686            10510
3             9000              9000     4737       4686            10510
4             9000              9000     4737       4686            10510
...            ...               ...      ...        ...              ...
46529         7500              7530     3577       3123             6700
46530         7500              7530     3577       3123             6700
46531         7500              7530     3577       3123             6700
46532         8068              8212     6286       7602            13888
46533         6572              6829     7973       9671            17644

       p1_crowns  ... p2_trophies p2_best_trophies p2_wins  p2_losses  \
0              1  ...        6860             6860    3174       2892
1              1  ...        6708             6708    3312       3994
2              1  ...        9000             9000   17541      14990
3              3  ...        9000             9000    1261       1015
4              2  ...        9000             9000   16221      12945
...          ...  ...         ...              ...     ...        ...
46529          1  ...        9000             9000    9511       9163
46530          0  ...        9000             9000    6475       5671
46531          0  ...        7830             7830    6137       5197
46532          0  ...        8040             8102    4084       3505
46533          0  ...        7004             7004    1434       1260

       p2_battle_count  p2_crowns  \
0                 7839          0
1                 8177          0
2                35975          3
3                 2301          2
4                38004          1
...                ...        ...
46529            18674          0
46530            12146          1
46531            11334          1
46532             7589          1
46533             2694          1

                                                p2_cards  \
0      [{"name": "Firecracker", "id": 26000064, "leve...
1      [{"name": "Valkyrie", "id": 26000011, "level":...
2      [{"name": "Royal Recruits", "id": 26000047, "l...
3      [{"name": "Firecracker", "id": 26000064, "leve...
4      [{"name": "Bats", "id": 26000049, "level": 14,...
...                                                  ...
46529  [{"name": "Royal Recruits", "id": 26000047, "l...
46530  [{"name": "Knight", "id": 26000000, "level": 1...
46531  [{"name": "Valkyrie", "id": 26000011, "level":...
46532  [{"name": "Mortar", "id": 27000002, "level": 1...
46533  [{"name": "Firecracker", "id": 26000064, "leve...

                                        p2_support_cards  p1_elixir_leaked  \
0      [{"name": "Tower Princess", "id": 159000000, "...              0.01
1      [{"name": "Tower Princess", "id": 159000000, "...              0.02
2      [{"name": "Tower Princess", "id": 159000000, "...              0.04
3      [{"name": "Dagger Duchess", "id": 159000002, "...              0.04
4      [{"name": "Cannoneer", "id": 159000001, "level...              0.01
...                                                  ...               ...
46529  [{"name": "Tower Princess", "id": 159000000, "...              0.00
46530  [{"name": "Dagger Duchess", "id": 159000002, "...              0.01
46531  [{"name": "Dagger Duchess", "id": 159000002, "...              0.17
46532  [{"name": "Tower Princess", "id": 159000000, "...              0.03
46533  [{"name": "Tower Princess", "id": 159000000, "...              0.03

      p2_elixir_leaked
0                 0.02
1                 0.01
2                 0.03
3                 0.05
4                 0.03
...                ...
46529             0.03
46530             0.01
46531             0.07
46532             0.01
46533             0.01

[46534 rows x 23 columns]

# Add `winner` output

In [133]:
# Add new winner column
df['winner'] = df.apply(lambda row: 1 if row['p1_crowns'] > row['p2_crowns'] else (2 if row['p2_crowns'] > row['p1_crowns'] else 0), axis=1)

In [134]:
# Counts for each type of winner
winner_counts = df['winner'].value_counts()

print("Winner counts:")
print(f"Player 1 Wins (1): {winner_counts.get(1, 0)}")
print(f"Player 2 Wins (2): {winner_counts.get(2, 0)}")

Winner counts:
Player 1 Wins (1): 25911
Player 2 Wins (2): 20623

In [135]:
# Class imbalance!
print("(Number of battles, number of columns): ", df.shape)
print("Column headings: ", df.columns)
print("Player 1 wins percentage : " + str(winner_counts.get(1,0) / (winner_counts.get(1,0) + winner_counts.get(2,0))))
print("Player 2 wins percentage : " + str(winner_counts.get(2,0) / (winner_counts.get(1,0) + winner_counts.get(2,0))))
df.head()

(Number of battles, number of columns):  (46534, 24)
Column headings:  Index(['id', 'battle_time', 'game_mode', 'p1_tag', 'p1_trophies',
       'p1_best_trophies', 'p1_wins', 'p1_losses', 'p1_battle_count',
       'p1_crowns', 'p1_elixir_leaked', 'p1_cards', 'p1_support_cards',
       'p2_tag', 'p2_trophies', 'p2_best_trophies', 'p2_wins', 'p2_losses',
       'p2_battle_count', 'p2_crowns', 'p2_elixir_leaked', 'p2_cards',
       'p2_support_cards', 'winner'],
      dtype='object')
Player 1 wins percentage : 0.5568186702196244
Player 2 wins percentage : 0.44318132978037567

,id,battle_time,game_mode,p1_tag,p1_trophies,p1_best_trophies,p1_wins,p1_losses,p1_battle_count,p1_crowns,...,p2_trophies,p2_best_trophies,p2_wins,p2_losses,p2_battle_count,p2_crowns,p2_elixir_leaked,p2_cards,p2_support_cards,winner
0,1,2024-04-08 14:32:06.000000,Ladder,2J200GLG8,6911,6942,3336,2107,9197,1,...,6860,6860,3174,2892,7839,0,3.00,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""...",1
1,3,2024-04-08 14:28:14.000000,Ranked1v1,2J200GLG8,6911,6942,3336,2107,9197,1,...,6708,6708,3312,3994,8177,0,1.75,"[{""name"": ""Valkyrie"", ""id"": 26000011, ""level"":...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""...",1
2,4,2024-04-08 15:29:20.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,1,...,9000,9000,17541,14990,35975,3,4.64,"[{""name"": ""Royal Recruits"", ""id"": 26000047, ""l...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""...",2
3,5,2024-04-08 15:24:27.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,3,...,9000,9000,1261,1015,2301,2,8.18,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Dagger Duchess"", ""id"": 159000002, ""...",1
4,6,2024-04-08 15:20:10.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,2,...,9000,9000,16221,12945,38004,1,4.41,"[{""name"": ""Bats"", ""id"": 26000049, ""level"": 14,...","[{""name"": ""Cannoneer"", ""id"": 159000001, ""level...",1

# Calculate win rate

When exporting the .csv dataset via a database management tool, we used a query to check, whether there are duplicates. Therefore we don't filter for duplicates in this jupyter notebook.

We continue by adding two more columns, that indicate the total win rate for each player. We use the already existing columns `p1_wins`, `p2_wins`, `p1_losses` and `p2_losses` to calculate them. It is important to note, that the win rates calculated here are win rates for all battles the players in question have ever played. The win rate can therefore not deducted by this dataset, since this includes only battles from april 2024 to september 2024.

In [136]:
df['p1_total_win_rate'] = (df['p1_wins'] / df['p1_losses']).round(2)
df['p2_total_win_rate'] = (df['p2_wins'] / df['p2_losses']).round(2)

In [137]:
print("Column headings: ", df.columns)
df.head()

Column headings:  Index(['id', 'battle_time', 'game_mode', 'p1_tag', 'p1_trophies',
       'p1_best_trophies', 'p1_wins', 'p1_losses', 'p1_battle_count',
       'p1_crowns', 'p1_elixir_leaked', 'p1_cards', 'p1_support_cards',
       'p2_tag', 'p2_trophies', 'p2_best_trophies', 'p2_wins', 'p2_losses',
       'p2_battle_count', 'p2_crowns', 'p2_elixir_leaked', 'p2_cards',
       'p2_support_cards', 'winner', 'p1_total_win_rate', 'p2_total_win_rate'],
      dtype='object')

,id,battle_time,game_mode,p1_tag,p1_trophies,p1_best_trophies,p1_wins,p1_losses,p1_battle_count,p1_crowns,...,p2_wins,p2_losses,p2_battle_count,p2_crowns,p2_elixir_leaked,p2_cards,p2_support_cards,winner,p1_total_win_rate,p2_total_win_rate
0,1,2024-04-08 14:32:06.000000,Ladder,2J200GLG8,6911,6942,3336,2107,9197,1,...,3174,2892,7839,0,3.00,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""...",1,1.58,1.10
1,3,2024-04-08 14:28:14.000000,Ranked1v1,2J200GLG8,6911,6942,3336,2107,9197,1,...,3312,3994,8177,0,1.75,"[{""name"": ""Valkyrie"", ""id"": 26000011, ""level"":...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""...",1,1.58,0.83
2,4,2024-04-08 15:29:20.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,1,...,17541,14990,35975,3,4.64,"[{""name"": ""Royal Recruits"", ""id"": 26000047, ""l...","[{""name"": ""Tower Princess"", ""id"": 159000000, ""...",2,1.01,1.17
3,5,2024-04-08 15:24:27.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,3,...,1261,1015,2301,2,8.18,"[{""name"": ""Firecracker"", ""id"": 26000064, ""leve...","[{""name"": ""Dagger Duchess"", ""id"": 159000002, ""...",1,1.01,1.24
4,6,2024-04-08 15:20:10.000000,Ranked1v1,RJCYQLJJ0,9000,9000,4737,4686,10510,2,...,16221,12945,38004,1,4.41,"[{""name"": ""Bats"", ""id"": 26000049, ""level"": 14,...","[{""name"": ""Cannoneer"", ""id"": 159000001, ""level...",1,1.01,1.25

# Normalization of `p1_win_rate` and `p2_win_rate`

We continue to normalize another pairs of columns, namely p1_total_win_rate and p2_total_win_rate with the same min-max-normalization algorithm.

In [90]:
columns_to_normalize = ['p1_total_win_rate', 'p2_total_win_rate']

# min-max normalization
for column in columns_to_normalize:
    min_value = df[column].min()
    max_value = df[column].max()

    if max_value - min_value != 0:
        df[column + '_normalized'] = ((df[column] - min_value) / (max_value - min_value)).round(2)
    else:
        df[column + '_normalized'] = 0

In [91]:
# Drop the original columns
df = df.drop(columns=columns_to_normalize)

# Rename normalized columns
normalized_columns = {column + '_normalized': column for column in columns_to_normalize}
df = df.rename(columns=normalized_columns)

In [92]:
# Reorder columns

all_columns = list(df.columns)

other_columns = [col for col in all_columns if not col.startswith('p1_') and not col.startswith('p2_')]
p1_columns = [col for col in all_columns if col.startswith('p1_')]
p2_columns = [col for col in all_columns if col.startswith('p2_')]

other_columns = sorted(other_columns)
p1_columns = sorted(p1_columns)
p2_columns = sorted(p2_columns)

new_column_order = other_columns + p1_columns + p2_columns
df = df[new_column_order]

In [93]:
print("\nColumn Names:")
print(df.columns.tolist())

print(df.head())

Column Names:
['battle_time', 'game_mode', 'id', 'winner', 'p1_battle_count', 'p1_best_trophies', 'p1_cards', 'p1_crowns', 'p1_elixir_leaked', 'p1_losses', 'p1_support_cards', 'p1_tag', 'p1_total_win_rate', 'p1_trophies', 'p1_wins', 'p2_battle_count', 'p2_best_trophies', 'p2_cards', 'p2_crowns', 'p2_elixir_leaked', 'p2_losses', 'p2_support_cards', 'p2_tag', 'p2_total_win_rate', 'p2_trophies', 'p2_wins']
                  battle_time  game_mode  id  winner  p1_battle_count  \
0  2024-04-08 14:32:06.000000     Ladder   1       1             9197
1  2024-04-08 14:28:14.000000  Ranked1v1   3       1             9197
2  2024-04-08 15:29:20.000000  Ranked1v1   4       2            10510
3  2024-04-08 15:24:27.000000  Ranked1v1   5       1            10510
4  2024-04-08 15:20:10.000000  Ranked1v1   6       1            10510

   p1_best_trophies                                           p1_cards  \
0              6942  [{"name": "Knight", "id": 26000000, "level": 1...
1              6942  [{"name": "Knight", "id": 26000000, "level": 1...
2              9000  [{"name": "Barbarians", "id": 26000008, "level...
3              9000  [{"name": "Barbarians", "id": 26000008, "level...
4              9000  [{"name": "Barbarians", "id": 26000008, "level...

   p1_crowns  p1_elixir_leaked  p1_losses  ... p2_best_trophies  \
0          1              0.01       2107  ...             6860
1          1              0.02       2107  ...             6708
2          1              0.04       4686  ...             9000
3          3              0.04       4686  ...             9000
4          2              0.01       4686  ...             9000

                                            p2_cards  p2_crowns  \
0  [{"name": "Firecracker", "id": 26000064, "leve...          0
1  [{"name": "Valkyrie", "id": 26000011, "level":...          0
2  [{"name": "Royal Recruits", "id": 26000047, "l...          3
3  [{"name": "Firecracker", "id": 26000064, "leve...          2
4  [{"name": "Bats", "id": 26000049, "level": 14,...          1

   p2_elixir_leaked  p2_losses  \
0              0.02       2892
1              0.01       3994
2              0.03      14990
3              0.05       1015
4              0.03      12945

                                    p2_support_cards     p2_tag  \
0  [{"name": "Tower Princess", "id": 159000000, "...  29LC802RC
1  [{"name": "Tower Princess", "id": 159000000, "...  PG0Q0Y0L9
2  [{"name": "Tower Princess", "id": 159000000, "...   CLPC08L0
3  [{"name": "Dagger Duchess", "id": 159000002, "...  2YQP0GYVQ
4  [{"name": "Cannoneer", "id": 159000001, "level...  8R0RPQJVV

  p2_total_win_rate  p2_trophies  p2_wins
0              0.13         6860     3174
1              0.09         6708     3312
2              0.13         9000    17541
3              0.14         9000     1261
4              0.14         9000    16221

[5 rows x 26 columns]

In [94]:
df.to_csv('battles_1st_approach_not_for_use.csv', index=False)

# One-Hot-Encoding for cards

We want to prepare the columns p1_cards, p2_cards, p1_support_cards, p2_support_cards for our ml algorithms. Therefore we encode the values with one-hot-encoding and create two columns for every card, that exists in the game. These columns indicate whether a card is part of the player's deck or not. There should be 8 columns with the value 1 for every player and another one to indicate which support card the player has used.

In [138]:
import ast
import json

# df for .csv files for cards and support cards
cards_df = pd.read_csv('/content/cards.csv')
support_cards_df = pd.read_csv('/content/support_cards.csv')

In [139]:
# Get all possible card ids for cards and support cards
card_ids = cards_df['id'].tolist()
support_card_ids = support_cards_df['id'].tolist()

# Init the One-Hot Columns
for card_id in card_ids:
    df[f'p1_has_card_{card_id}'] = 0
    df[f'p2_has_card_{card_id}'] = 0

for card_id in support_card_ids:
    df[f'p1_has_support_card_{card_id}'] = 0
    df[f'p2_has_support_card_{card_id}'] = 0

<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p2_has_card_{card_id}'] = 0
<ipython-input-139-54b7efb8b34c>:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'p1_has_card_{card_id}'] = 0

In [140]:
# Parse method for the JSON strings
def parse_json_column(json_str):
    try:
        # Some strings may need to be evaluated as literals
        return json.loads(json_str)
    except json.JSONDecodeError:
        try:
            return ast.literal_eval(json_str)
        except:
            return []

df['p1_cards_parsed'] = df['p1_cards'].apply(parse_json_column)
df['p2_cards_parsed'] = df['p2_cards'].apply(parse_json_column)
df['p1_support_cards_parsed'] = df['p1_support_cards'].apply(parse_json_column)
df['p2_support_cards_parsed'] = df['p2_support_cards'].apply(parse_json_column)

<ipython-input-140-538e142dfe04>:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['p1_cards_parsed'] = df['p1_cards'].apply(parse_json_column)
<ipython-input-140-538e142dfe04>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['p2_cards_parsed'] = df['p2_cards'].apply(parse_json_column)
<ipython-input-140-538e142dfe04>:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['p1_support_cards_parsed'] = df['p1_support_cards'].apply(parse_json_column)
<ipython-input-140-538e142dfe04>:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['p2_support_cards_parsed'] = df['p2_support_cards'].apply(parse_json_column)

In [141]:
# Populate One-Hot encoded cols

def one_hot_encode_cards(row, support_cards=False):
    p1_card_key = 'p1_support_cards_parsed' if support_cards else 'p1_cards_parsed'
    p2_card_key = 'p2_support_cards_parsed' if support_cards else 'p2_cards_parsed'

    p1_column_prefix = 'p1_has_support_card_' if support_cards else 'p1_has_card_'
    p2_column_prefix = 'p2_has_support_card_' if support_cards else 'p2_has_card_'

    p1_card_ids_in_battle = {card['id'] for card in row[p1_card_key]}
    for card_id in p1_card_ids_in_battle:
        if f'{p1_column_prefix}{card_id}' in df.columns:
            df.at[row.name, f'{p1_column_prefix}{card_id}'] = 1

    p2_card_ids_in_battle = {card['id'] for card in row[p2_card_key]}
    for card_id in p2_card_ids_in_battle:
        if f'{p2_column_prefix}{card_id}' in df.columns:
            df.at[row.name, f'{p2_column_prefix}{card_id}'] = 1

In [142]:
# Apply the function to each row
df.apply(one_hot_encode_cards, axis=1)
df.apply(lambda row: one_hot_encode_cards(row, support_cards=True), axis=1)

0        None
1        None
2        None
3        None
4        None
         ...
46529    None
46530    None
46531    None
46532    None
46533    None
Length: 46534, dtype: object

In [100]:
# Clean up
df = df.drop(columns=[
    'p1_cards_parsed', 'p2_cards_parsed',
    'p1_support_cards_parsed', 'p2_support_cards_parsed'
])

In [101]:
print("(Number of battles, number of columns): ", df.shape)
print("Column headings: ", df.columns)
df.head()

(Number of battles, number of columns):  (46534, 266)
Column headings:  Index(['battle_time', 'game_mode', 'id', 'winner', 'p1_battle_count',
       'p1_best_trophies', 'p1_cards', 'p1_crowns', 'p1_elixir_leaked',
       'p1_losses',
       ...
       'p1_has_card_28000024', 'p2_has_card_28000024',
       'p1_has_support_card_159000000', 'p2_has_support_card_159000000',
       'p1_has_support_card_159000001', 'p2_has_support_card_159000001',
       'p1_has_support_card_159000002', 'p2_has_support_card_159000002',
       'p1_has_support_card_159000003', 'p2_has_support_card_159000003'],
      dtype='object', length=266)

,battle_time,game_mode,id,winner,p1_battle_count,p1_best_trophies,p1_cards,p1_crowns,p1_elixir_leaked,p1_losses,...,p1_has_card_28000024,p2_has_card_28000024,p1_has_support_card_159000000,p2_has_support_card_159000000,p1_has_support_card_159000001,p2_has_support_card_159000001,p1_has_support_card_159000002,p2_has_support_card_159000002,p1_has_support_card_159000003,p2_has_support_card_159000003
0,2024-04-08 14:32:06.000000,Ladder,1,1,9197,6942,"[{""name"": ""Knight"", ""id"": 26000000, ""level"": 1...",1,0.01,2107,...,0,0,1,1,0,0,0,0,0,0
1,2024-04-08 14:28:14.000000,Ranked1v1,3,1,9197,6942,"[{""name"": ""Knight"", ""id"": 26000000, ""level"": 1...",1,0.02,2107,...,0,0,1,1,0,0,0,0,0,0
2,2024-04-08 15:29:20.000000,Ranked1v1,4,2,10510,9000,"[{""name"": ""Barbarians"", ""id"": 26000008, ""level...",1,0.04,4686,...,0,0,1,1,0,0,0,0,0,0
3,2024-04-08 15:24:27.000000,Ranked1v1,5,1,10510,9000,"[{""name"": ""Barbarians"", ""id"": 26000008, ""level...",3,0.04,4686,...,0,0,1,0,0,0,0,1,0,0
4,2024-04-08 15:20:10.000000,Ranked1v1,6,1,10510,9000,"[{""name"": ""Barbarians"", ""id"": 26000008, ""level...",2,0.01,4686,...,0,0,1,0,0,1,0,0,0,0

# Add avg elixir cost per deck

We want to calculate the average elixir cost for the entire deck for each player. We make use of our cards_df to retrieve pairs to id and elixirCost for each card. Since each deck has 8 cards, we divide the sum of the elixir cost for each card by 8 and round it to two decimal places.

In [102]:
# Create a dictionary mapping card IDs to elixir costs
card_elixir_costs = cards_df.set_index('id')['elixirCost'].to_dict()

In [103]:
# Get list of columns per player
all_columns = df.columns
p1_card_columns = [col for col in all_columns if col.startswith('p1_has_card_')]
p2_card_columns = [col for col in all_columns if col.startswith('p2_has_card_')]

In [104]:
# Extract card IDs from column names and map card ids to elixir costs per player
p1_card_ids = [int(col.replace('p1_has_card_', '')) for col in p1_card_columns]
p2_card_ids = [int(col.replace('p2_has_card_', '')) for col in p2_card_columns]

p1_elixir_costs = [card_elixir_costs.get(card_id, 0) for card_id in p1_card_ids]
p2_elixir_costs = [card_elixir_costs.get(card_id, 0) for card_id in p2_card_ids]

In [105]:
# Multiply each column by the corresponding elixir cost per player
p1_cards_df = df[p1_card_columns]
p1_cards_elixir = p1_cards_df.mul(p1_elixir_costs)
p1_total_elixir = p1_cards_elixir.sum(axis=1)

p2_cards_df = df[p2_card_columns]
p2_cards_elixir = p2_cards_df.mul(p2_elixir_costs)
p2_total_elixir = p2_cards_elixir.sum(axis=1)

In [106]:
# Calc avg elixir cost per player
num_cards_per_player = 8
df['p1_avg_elixir_cost'] = (p1_total_elixir / num_cards_per_player).round(2)
df['p2_avg_elixir_cost'] = (p2_total_elixir / num_cards_per_player).round(2)

<ipython-input-106-d1b9529d1d37>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['p1_avg_elixir_cost'] = (p1_total_elixir / num_cards_per_player).round(2)
<ipython-input-106-d1b9529d1d37>:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['p2_avg_elixir_cost'] = (p2_total_elixir / num_cards_per_player).round(2)

In [107]:
print("(Number of battles, number of columns):", df.shape)

(Number of battles, number of columns): (46534, 268)

In [108]:
# Export csv for 1st approach for EDA. This .csv is computed only then correctly if the cells are computed in a specific order
df.to_csv('battles_1st_approach_eda.csv', index=False)

# Normalization elixir_cost

We normalize p1_avg_elixir_cost and p2_avg_elixir_cost by applying
min-max-normalization and add the suffix _normalized to the column names.

In [109]:
columns_to_normalize = ['p1_avg_elixir_cost', 'p2_avg_elixir_cost']

In [110]:
for column in columns_to_normalize:
    min_value = df[column].min()
    max_value = df[column].max()

    df[column + '_normalized'] = ((df[column] - min_value) / (max_value - min_value)).round(2)

<ipython-input-110-41a3561b4823>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column + '_normalized'] = ((df[column] - min_value) / (max_value - min_value)).round(2)
<ipython-input-110-41a3561b4823>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[column + '_normalized'] = ((df[column] - min_value) / (max_value - min_value)).round(2)

In [111]:
# Drop the original columns, rename normalize cols
df = df.drop(columns=columns_to_normalize)
normalized_columns = {column + '_normalized': column for column in columns_to_normalize}
battles_df = df.rename(columns=normalized_columns)

In [112]:
df.head()

,battle_time,game_mode,id,winner,p1_battle_count,p1_best_trophies,p1_cards,p1_crowns,p1_elixir_leaked,p1_losses,...,p1_has_support_card_159000000,p2_has_support_card_159000000,p1_has_support_card_159000001,p2_has_support_card_159000001,p1_has_support_card_159000002,p2_has_support_card_159000002,p1_has_support_card_159000003,p2_has_support_card_159000003,p1_avg_elixir_cost_normalized,p2_avg_elixir_cost_normalized
0,2024-04-08 14:32:06.000000,Ladder,1,1,9197,6942,"[{""name"": ""Knight"", ""id"": 26000000, ""level"": 1...",1,0.01,2107,...,1,1,0,0,0,0,0,0,0.54,0.47
1,2024-04-08 14:28:14.000000,Ranked1v1,3,1,9197,6942,"[{""name"": ""Knight"", ""id"": 26000000, ""level"": 1...",1,0.02,2107,...,1,1,0,0,0,0,0,0,0.54,0.50
2,2024-04-08 15:29:20.000000,Ranked1v1,4,2,10510,9000,"[{""name"": ""Barbarians"", ""id"": 26000008, ""level...",1,0.04,4686,...,1,1,0,0,0,0,0,0,0.57,0.50
3,2024-04-08 15:24:27.000000,Ranked1v1,5,1,10510,9000,"[{""name"": ""Barbarians"", ""id"": 26000008, ""level...",3,0.04,4686,...,1,0,0,0,0,1,0,0,0.57,0.47
4,2024-04-08 15:20:10.000000,Ranked1v1,6,1,10510,9000,"[{""name"": ""Barbarians"", ""id"": 26000008, ""level...",2,0.01,4686,...,1,0,0,1,0,0,0,0,0.57,0.33

We sort our columns, so that we have our more general columns first, then columns related to player 1 and then columns related to player 2.

In [113]:
all_columns = list(df.columns)

other_columns = [col for col in all_columns if not (col.startswith('p1_') or col.startswith('p2_'))]
p1_columns = [col for col in all_columns if col.startswith('p1_')]
p2_columns = [col for col in all_columns if col.startswith('p2_')]

other_columns = sorted(other_columns)
p1_columns = sorted(p1_columns)
p2_columns = sorted(p2_columns)

new_column_order = other_columns + p1_columns + p2_columns
df = df[new_column_order]

In [114]:
print("DataFrame Head:")
print(df.head())

print("\nColumn Names:")
print(df.columns.tolist())

DataFrame Head:
                  battle_time  game_mode  id  winner  \
0  2024-04-08 14:32:06.000000     Ladder   1       1
1  2024-04-08 14:28:14.000000  Ranked1v1   3       1
2  2024-04-08 15:29:20.000000  Ranked1v1   4       2
3  2024-04-08 15:24:27.000000  Ranked1v1   5       1
4  2024-04-08 15:20:10.000000  Ranked1v1   6       1

   p1_avg_elixir_cost_normalized  p1_battle_count  p1_best_trophies  \
0                           0.54             9197              6942
1                           0.54             9197              6942
2                           0.57            10510              9000
3                           0.57            10510              9000
4                           0.57            10510              9000

                                            p1_cards  p1_crowns  \
0  [{"name": "Knight", "id": 26000000, "level": 1...          1
1  [{"name": "Knight", "id": 26000000, "level": 1...          1
2  [{"name": "Barbarians", "id": 26000008, "level...          1
3  [{"name": "Barbarians", "id": 26000008, "level...          3
4  [{"name": "Barbarians", "id": 26000008, "level...          2

   p1_elixir_leaked  ...  p2_has_support_card_159000000  \
0              0.01  ...                              1
1              0.02  ...                              1
2              0.04  ...                              1
3              0.04  ...                              0
4              0.01  ...                              0

   p2_has_support_card_159000001  p2_has_support_card_159000002  \
0                              0                              0
1                              0                              0
2                              0                              0
3                              0                              1
4                              1                              0

   p2_has_support_card_159000003  p2_losses  \
0                              0       2892
1                              0       3994
2                              0      14990
3                              0       1015
4                              0      12945

                                    p2_support_cards     p2_tag  \
0  [{"name": "Tower Princess", "id": 159000000, "...  29LC802RC
1  [{"name": "Tower Princess", "id": 159000000, "...  PG0Q0Y0L9
2  [{"name": "Tower Princess", "id": 159000000, "...   CLPC08L0
3  [{"name": "Dagger Duchess", "id": 159000002, "...  2YQP0GYVQ
4  [{"name": "Cannoneer", "id": 159000001, "level...  8R0RPQJVV

   p2_total_win_rate  p2_trophies  p2_wins
0               0.13         6860     3174
1               0.09         6708     3312
2               0.13         9000    17541
3               0.14         9000     1261
4               0.14         9000    16221

[5 rows x 268 columns]

Column Names:
['battle_time', 'game_mode', 'id', 'winner', 'p1_avg_elixir_cost_normalized', 'p1_battle_count', 'p1_best_trophies', 'p1_cards', 'p1_crowns', 'p1_elixir_leaked', 'p1_has_card_26000000', 'p1_has_card_26000001', 'p1_has_card_26000002', 'p1_has_card_26000003', 'p1_has_card_26000004', 'p1_has_card_26000005', 'p1_has_card_26000006', 'p1_has_card_26000007', 'p1_has_card_26000008', 'p1_has_card_26000009', 'p1_has_card_26000010', 'p1_has_card_26000011', 'p1_has_card_26000012', 'p1_has_card_26000013', 'p1_has_card_26000014', 'p1_has_card_26000015', 'p1_has_card_26000016', 'p1_has_card_26000017', 'p1_has_card_26000018', 'p1_has_card_26000019', 'p1_has_card_26000020', 'p1_has_card_26000021', 'p1_has_card_26000022', 'p1_has_card_26000023', 'p1_has_card_26000024', 'p1_has_card_26000025', 'p1_has_card_26000026', 'p1_has_card_26000027', 'p1_has_card_26000028', 'p1_has_card_26000029', 'p1_has_card_26000030', 'p1_has_card_26000031', 'p1_has_card_26000032', 'p1_has_card_26000033', 'p1_has_card_26000034', 'p1_has_card_26000035', 'p1_has_card_26000036', 'p1_has_card_26000037', 'p1_has_card_26000038', 'p1_has_card_26000039', 'p1_has_card_26000040', 'p1_has_card_26000041', 'p1_has_card_26000042', 'p1_has_card_26000043', 'p1_has_card_26000044', 'p1_has_card_26000045', 'p1_has_card_26000046', 'p1_has_card_26000047', 'p1_has_card_26000048', 'p1_has_card_26000049', 'p1_has_card_26000050', 'p1_has_card_26000051', 'p1_has_card_26000052', 'p1_has_card_26000053', 'p1_has_card_26000054', 'p1_has_card_26000055', 'p1_has_card_26000056', 'p1_has_card_26000057', 'p1_has_card_26000058', 'p1_has_card_26000059', 'p1_has_card_26000060', 'p1_has_card_26000061', 'p1_has_card_26000062', 'p1_has_card_26000063', 'p1_has_card_26000064', 'p1_has_card_26000065', 'p1_has_card_26000067', 'p1_has_card_26000068', 'p1_has_card_26000069', 'p1_has_card_26000072', 'p1_has_card_26000074', 'p1_has_card_26000077', 'p1_has_card_26000080', 'p1_has_card_26000083', 'p1_has_card_26000084', 'p1_has_card_26000085', 'p1_has_card_26000087', 'p1_has_card_26000093', 'p1_has_card_26000095', 'p1_has_card_26000096', 'p1_has_card_26000097', 'p1_has_card_26000099', 'p1_has_card_27000000', 'p1_has_card_27000001', 'p1_has_card_27000002', 'p1_has_card_27000003', 'p1_has_card_27000004', 'p1_has_card_27000005', 'p1_has_card_27000006', 'p1_has_card_27000007', 'p1_has_card_27000008', 'p1_has_card_27000009', 'p1_has_card_27000010', 'p1_has_card_27000012', 'p1_has_card_27000013', 'p1_has_card_28000000', 'p1_has_card_28000001', 'p1_has_card_28000002', 'p1_has_card_28000003', 'p1_has_card_28000004', 'p1_has_card_28000005', 'p1_has_card_28000006', 'p1_has_card_28000007', 'p1_has_card_28000008', 'p1_has_card_28000009', 'p1_has_card_28000010', 'p1_has_card_28000011', 'p1_has_card_28000012', 'p1_has_card_28000013', 'p1_has_card_28000014', 'p1_has_card_28000015', 'p1_has_card_28000016', 'p1_has_card_28000017', 'p1_has_card_28000018', 'p1_has_card_28000023', 'p1_has_card_28000024', 'p1_has_support_card_159000000', 'p1_has_support_card_159000001', 'p1_has_support_card_159000002', 'p1_has_support_card_159000003', 'p1_losses', 'p1_support_cards', 'p1_tag', 'p1_total_win_rate', 'p1_trophies', 'p1_wins', 'p2_avg_elixir_cost_normalized', 'p2_battle_count', 'p2_best_trophies', 'p2_cards', 'p2_crowns', 'p2_elixir_leaked', 'p2_has_card_26000000', 'p2_has_card_26000001', 'p2_has_card_26000002', 'p2_has_card_26000003', 'p2_has_card_26000004', 'p2_has_card_26000005', 'p2_has_card_26000006', 'p2_has_card_26000007', 'p2_has_card_26000008', 'p2_has_card_26000009', 'p2_has_card_26000010', 'p2_has_card_26000011', 'p2_has_card_26000012', 'p2_has_card_26000013', 'p2_has_card_26000014', 'p2_has_card_26000015', 'p2_has_card_26000016', 'p2_has_card_26000017', 'p2_has_card_26000018', 'p2_has_card_26000019', 'p2_has_card_26000020', 'p2_has_card_26000021', 'p2_has_card_26000022', 'p2_has_card_26000023', 'p2_has_card_26000024', 'p2_has_card_26000025', 'p2_has_card_26000026', 'p2_has_card_26000027', 'p2_has_card_26000028', 'p2_has_card_26000029', 'p2_has_card_26000030', 'p2_has_card_26000031', 'p2_has_card_26000032', 'p2_has_card_26000033', 'p2_has_card_26000034', 'p2_has_card_26000035', 'p2_has_card_26000036', 'p2_has_card_26000037', 'p2_has_card_26000038', 'p2_has_card_26000039', 'p2_has_card_26000040', 'p2_has_card_26000041', 'p2_has_card_26000042', 'p2_has_card_26000043', 'p2_has_card_26000044', 'p2_has_card_26000045', 'p2_has_card_26000046', 'p2_has_card_26000047', 'p2_has_card_26000048', 'p2_has_card_26000049', 'p2_has_card_26000050', 'p2_has_card_26000051', 'p2_has_card_26000052', 'p2_has_card_26000053', 'p2_has_card_26000054', 'p2_has_card_26000055', 'p2_has_card_26000056', 'p2_has_card_26000057', 'p2_has_card_26000058', 'p2_has_card_26000059', 'p2_has_card_26000060', 'p2_has_card_26000061', 'p2_has_card_26000062', 'p2_has_card_26000063', 'p2_has_card_26000064', 'p2_has_card_26000065', 'p2_has_card_26000067', 'p2_has_card_26000068', 'p2_has_card_26000069', 'p2_has_card_26000072', 'p2_has_card_26000074', 'p2_has_card_26000077', 'p2_has_card_26000080', 'p2_has_card_26000083', 'p2_has_card_26000084', 'p2_has_card_26000085', 'p2_has_card_26000087', 'p2_has_card_26000093', 'p2_has_card_26000095', 'p2_has_card_26000096', 'p2_has_card_26000097', 'p2_has_card_26000099', 'p2_has_card_27000000', 'p2_has_card_27000001', 'p2_has_card_27000002', 'p2_has_card_27000003', 'p2_has_card_27000004', 'p2_has_card_27000005', 'p2_has_card_27000006', 'p2_has_card_27000007', 'p2_has_card_27000008', 'p2_has_card_27000009', 'p2_has_card_27000010', 'p2_has_card_27000012', 'p2_has_card_27000013', 'p2_has_card_28000000', 'p2_has_card_28000001', 'p2_has_card_28000002', 'p2_has_card_28000003', 'p2_has_card_28000004', 'p2_has_card_28000005', 'p2_has_card_28000006', 'p2_has_card_28000007', 'p2_has_card_28000008', 'p2_has_card_28000009', 'p2_has_card_28000010', 'p2_has_card_28000011', 'p2_has_card_28000012', 'p2_has_card_28000013', 'p2_has_card_28000014', 'p2_has_card_28000015', 'p2_has_card_28000016', 'p2_has_card_28000017', 'p2_has_card_28000018', 'p2_has_card_28000023', 'p2_has_card_28000024', 'p2_has_support_card_159000000', 'p2_has_support_card_159000001', 'p2_has_support_card_159000002', 'p2_has_support_card_159000003', 'p2_losses', 'p2_support_cards', 'p2_tag', 'p2_total_win_rate', 'p2_trophies', 'p2_wins']

Finally we export our battles dataset for further exploratory data analysis and machine learning.

In [118]:
# Drop not relevant columns
columns_to_drop = [
    'battle_time', 'id', 'p1_cards', 'p2_cards', 'p1_support_cards', 'p2_support_cards',
    'game_mode', 'p1_battle_count', 'p1_best_trophies', 'p1_crowns', 'p1_losses',
    'p1_tag', 'p1_trophies', 'p1_wins', 'p2_battle_count', 'p2_best_trophies',
    'p2_crowns', 'p2_losses', 'p2_tag', 'p2_trophies', 'p2_wins'
]

df = df.drop(columns=columns_to_drop)

KeyError: "['battle_time', 'id', 'p1_cards', 'p2_cards', 'p1_support_cards', 'p2_support_cards', 'game_mode', 'p1_battle_count', 'p1_best_trophies', 'p1_crowns', 'p1_losses', 'p1_tag', 'p1_trophies', 'p1_wins', 'p2_battle_count', 'p2_best_trophies', 'p2_crowns', 'p2_losses', 'p2_tag', 'p2_trophies', 'p2_wins'] not found in axis"

In [117]:
# Export .csv for ml 1st approach
df.to_csv('battles_1st_approach.csv', index=False)